Update CI to test 9-digits capcode as well

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -24,11 +24,22 @@ jobs:
 
     - name: Build demos
       run:  cd demos && make
-    - name: Check for correctness
+    - name: Check short capcode correctness
       run: |
         cd demos
         hash1=$(printf "1234567:HACK THE PLANET" | ./encode_file | md5sum | awk '{print $1}')
-        hash2=$(md5sum ../tests/reference_output.bin | awk '{print $1}')
+        hash2=$(md5sum ../tests/7digit_output.bin | awk '{print $1}')
+        if [ "$hash1" = "$hash2" ]; then
+          echo "OK"
+        else
+          echo "FAIL"
+          exit 1
+        fi
+    - name: Check long capcode correctness
+      run: |
+        cd demos
+        hash1=$(printf "123456789:HACKING TO THE GATE" | ./encode_file | md5sum | awk '{print $1}')
+        hash2=$(md5sum ../tests/9digit_output.bin | awk '{print $1}')
         if [ "$hash1" = "$hash2" ]; then
           echo "OK"
         else
